### ISSUE TITLE
Click on "copy command"

### ISSUE THREAD

**Issue by XRedShark** [asylumexp/Proxmox#33]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

when I click "copy command", it copies "test", not the command.
Browser Chrome on linux
Thank you! Great work!

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Ubuntu 20.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/asylumexp/Proxmox/assets/48174647/0294092b-ee28-4a63-b485-4ec8aa9facf5)

**Comment by asylumexp** [comment]
Fix was in a seperate branch, merging into main now.

**Comment by asylumexp** [comment]
Fix has been deployed, may take a bit for vercel to update the main URL with the changes
