### ISSUE TITLE
Error installing InfluxDB

### ISSUE THREAD

**Issue by euphguy** [asylumexp/Proxmox#45]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

Error when installing InfluxDB, version 1 specifically. Typo in script is pointing to amd version of Chronograf. 
InfluxDB-install.sh, line 44:
$STD dpkg -i chronograf_1.10.1_amd64.deb

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

**Comment by asylumexp** [comment]
I'll have a look now

**Comment by asylumexp** [comment]
Thanks for pointing this out, I must've only tested InfluxDB v2 when i first ported the script.
