### ISSUE TITLE
Unable to start nginx in frigate 0.14

### ISSUE THREAD

**Issue by tom0010** [asylumexp/Proxmox#67]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

When creating a new frigate container, nginx is not able to start:

```bash
root@frigate14:~# service nginx status
● nginx.service - Nginx service
     Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2024-08-09 13:07:57 BST; 908ms ago
    Process: 50093 ExecStartPre=rm /dev/shm/logs/nginx/current (code=exited, status=0/SUCCESS)
    Process: 50094 ExecStart=bash /opt/frigate/docker/main/rootfs/etc/s6-overlay/s6-rc.d/nginx/run (code=exited, status=127)
   Main PID: 50094 (code=exited, status=127)
        CPU: 194ms

Aug 09 13:07:57 frigate14 systemd[1]: nginx.service: Main process exited, code=exited, status=127/n/a
Aug 09 13:07:57 frigate14 systemd[1]: nginx.service: Failed with result 'exit-code'.
root@frigate14:~# tail -f /dev/shm/logs/nginx/current
[INFO] Starting NGINX...
/opt/frigate/docker/main/rootfs/etc/s6-overlay/s6-rc.d/nginx/run: line 84: tempio: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Getting:
`tempio: command not found`

Maybe related to https://github.com/blakeblackshear/frigate/discussions/11755 

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### Please provide detailed steps to reproduce the issue.

Frigate has released a new version, 0.14.0, I am unable to create this container.

Maybe worth noting that I stumbled into this error again:
```bash
 ✓ Built Nginx
 ✓ Configured Services
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 |0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
 ✓ Cleaned
 -400 Parameter verification failed.rces   
memory: unable to hotplug memory: trying to change memory cgroup values: container not running

pct set <vmid> [OPTIONS]
 |
[ERROR] in line 69: exit code 0: while executing command pct set $CTID -memory 1024
```

Which was fixed in https://github.com/asylumexp/Proxmox/issues/64 

I have tried to create the container multiple times using advanced and default settings FYI. 

Inside of the container I also tried to start nginx manually, however frigate seems to restart/retry anyway, so this is a bit trivial.

**Comment by asylumexp** [comment]
I’ll merge a fix for the first issue in a min from upstream, I’ll figure out the pct command tmr as I haven’t been able to replicate it myself.

**Comment by asylumexp** [comment]
Issue addressed in https://github.com/asylumexp/Proxmox/commit/e79c521c7cec6a00605dffa21ec21914e1a9436c

will figure out the other issue tomorrow
