### ISSUE TITLE
Debian 12 - NanoPi R5C Unsupported machine

### ISSUE THREAD

**Issue by FrozenGamesYT** [asylumexp/Proxmox#86]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

NanoPi r5c being unsupported machine while proxmox itself is running on debian 12.

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### Please provide detailed steps to reproduce the issue.

Installing Debian 12 VM on NanoPi R5C through the script

**Comment by asylumexp** [comment]
Can you give some of the errors you encountered?

**Comment by FrozenGamesYT** [comment]
> Can you give some of the errors you encountered?


Using Advanced Settings
Virtual Machine ID: 102
Using Machine Type: q35
Using Disk Cache: None
Using Hostname: debian
Using CPU Model: Host
Allocated Cores: 1
Allocated RAM: 2048
Using Bridge: bridge
Using MAC Address: 02:B3:80:C8:E9:56
Using Vlan: Default
Using Interface MTU Size: Default
Start VM when completed: yes
Creating a Debian 12 VM using the above advanced settings
 ✓ Using local for Storage Location.
 ✓ Virtual Machine ID is 102.
 ✓ https://cloud.debian.org/images/cloud/bookworm/20240507-1740/debian-12-nocloud-arm64-20240507-1740.qcow2
 ✓ Downloaded debian-12-nocloud-arm64-20240507-1740.qcow2
 ✓ Created a Debian 12 VM (debian)
 - Starting Debian 12 VM...kvm: unsupported machine type
Use -machine help to list supported machines
start failed: QEMU exited with code 1

[ERROR] in line 412: exit code 255: while executing command qm start $VMID

**Comment by asylumexp** [comment]
Are you able to run `uname -m` for me please to make sure its aarch64?

**Comment by FrozenGamesYT** [comment]
> Are you able to run `uname -m` for me please to make sure its aarch64?

uname -m:
`aarch64`

**Comment by asylumexp** [comment]
try i440fx machine type in script advanced mode, if that works for you then ill get rid of q35 from script
