### ISSUE TITLE
raspberry pi 5 - proxmox, running ngingx-manager script fails on some python libs

### ISSUE THREAD

**Issue by HollandHards** [asylumexp/Proxmox#87]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

running; bash -c "$(wget -qLO - https://github.com/asylumexp/Proxmox/raw/main/ct/nginxproxymanager.sh)"
as root user, from 'host' (debian bookworm) results in some error about python dependence 

tried different OS options, privileged and unprivileged, my hosts system seems to be up2date. run the 'post install script'

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

  copying certbot_dns_multi/_internal/bridge/main.go -> build/lib.linux-aarch64-cpython-312/certbot_dns_multi/_internal/bridge
      running build_ext
      $ GOPATH=/tmp/tmpy12cly_l go get -d
      error: [Errno 2] No such file or directory: 'go'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for certbot-dns-multi
 doneuilding wheel for configobj (pyproject.toml) ... -
  Created wheel for configobj: filename=configobj-5.0.9-py2.py3-none-any.whl size=35615 sha256=718135454b4d2e079bc1b86ae4e1c92f770d3547f850082509db1109f6d35909
  Stored in directory: /root/.cache/pip/wheels/07/5a/10/d2fe92a9f4c6a57c0b75d362bd02b79c4cf5a6cdcadacd1c5f
Successfully built configobj
Failed to build certbot-dns-multi
ERROR: Could not build wheels for certbot-dns-multi, which is required to install pyproject.toml-based projects
 |
[ERROR] in line 42: exit code 0: while executing command $STD pip3 install certbot certbot-dns-multi

### Please provide detailed steps to reproduce the issue.

running; bash -c "$(wget -qLO - https://github.com/asylumexp/Proxmox/raw/main/ct/nginxproxymanager.sh)"

results in 'failed' install of VM

**Comment by FrozenGamesYT** [comment]
Happens on NanoPi R5C as well.

**Comment by asylumexp** [comment]
I'll have a look at this now

**Comment by FrozenGamesYT** [comment]
Now after the commits the script doesn't start at all.

![image](https://github.com/user-attachments/assets/a385d8e2-30e5-41f3-aabc-392fb2685855)

**Comment by asylumexp** [comment]
Just create a docker lxc and start it with that, a dependency isn't building and I can't figure it out

**Comment by asylumexp** [comment]
Nevermind, seems to be fixed now with https://github.com/asylumexp/Proxmox/commit/e7cca5c77963ab5195cbc29a03cb6ed4475a65db

**Comment by FrozenGamesYT** [comment]
> Nevermind, seems to be fixed now with [e7cca5c](https://github.com/asylumexp/Proxmox/commit/e7cca5c77963ab5195cbc29a03cb6ed4475a65db)

Not sure why, but the script still doesn't want to start, it just goes into a new line. What should I do to get around this?

![image](https://github.com/user-attachments/assets/6ac0ea0f-c5cf-4b1d-87c6-1bdacbfaa967)

**Comment by asylumexp** [comment]
do any of the other scripts work?

**Comment by FrozenGamesYT** [comment]
> do any of the other scripts work?

tried wireguard script. does the same:

![image](https://github.com/user-attachments/assets/22248a69-d12e-4b78-9ca6-7ad144b47e2f)

**Comment by asylumexp** [comment]
try checking to see if your computer is able to access github, or has internet, because that likely means that it can't access GitHub

**Comment by FrozenGamesYT** [comment]
> try checking to see if your computer is able to access github, or has internet, because that likely means that it can't access GitHub

had a conflict of firewall rules for dns. all good now, thanks.

**Comment by FrozenGamesYT** [comment]
> try checking to see if your computer is able to access github, or has internet, because that likely means that it can't access GitHub

the node-sass package is deprecated which makes the script not working.

**Comment by asylumexp** [comment]
yep once im able to properly test scripts again I’ll fix this

**Comment by asylumexp** [comment]
> the node-sass package is deprecated which makes the script not working.

Are you able to test now @FrozenGamesYT, it successfully created the lxc on my machine.
