### ISSUE TITLE
FlareSolverr dependencies install failing because of missing chromium-common

### ISSUE THREAD

**Issue by the-bukkit** [asylumexp/Proxmox#90]
### Please verify that you have read and understood the guidelines.

Yes

### A clear and concise description of the issue.

I'm trying to install FlareSolverr with the script. It runs perfectly until it's trying to install dependencies.

Running it with verbose gives the following error:
```
Package chromium-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '128.0.6613.84-1~deb12u1' for 'chromium-common' was not found

[ERROR] in line 27: exit code 0: while executing command $STD apt-get install -y chromium-common=128.0.6613.84-1~deb12u
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![grafik](https://github.com/user-attachments/assets/c7f00968-36bf-43aa-9bb2-6bd7a095720a)

### Please provide detailed steps to reproduce the issue.

Just run the FlareSolverr script and use the default settings

**Comment by asylumexp** [comment]
yeah I know what the issue is I’ll try fix it right now
