### ISSUE TITLE
Prometheus install [ERROR]

### ISSUE THREAD

**Issue by regiapriandi012** [asylumexp/Proxmox#92]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I have installation error of use Installation Prometheus Script,

```
-mv: cannot stat 'consoles/': No such file or directory
mv: cannot stat 'console_libraries/': No such file or directory

[ERROR] in line 32: exit code 0: while executing command mv consoles/ console_libraries/ /etc/prometheus/
```

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

![image](https://github.com/user-attachments/assets/29076efe-e854-45f0-bbe0-1c6a9b14f696)

### Please provide detailed steps to reproduce the issue.

I have use the script for install Prometheus,
bash -c "$(wget -qLO - https://github.com/asylumexp/Proxmox/raw/main/ct/prometheus.sh)"

**Comment by asylumexp** [comment]
I’ll work on fixing this after December 10th, when I can do work again.
