### ISSUE TITLE
AgentDVR script not working

### ISSUE THREAD

**Issue by kgsrirama** [asylumexp/Proxmox#96]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

I am getting below error when trying to install AgentDVR "No zipfiles found"

### What settings are you currently utilizing?

Advanced Settings

### Which Linux distribution are you employing?

Ubuntu 22.04

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

`Creating config file /etc/ssh/sshd_config with new version
 /Created symlink /etc/systemd/system/sshd.service → /lib/systemd/system/ssh.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ssh.service → /lib/systemd/system/ssh.service.
 /rescue-ssh.target is a disabled or a static unit, not starting it.
 |ssh.socket is a disabled or a static unit, not starting it.
 -Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
 ✓ Installed Dependencies
 -unzip:  cannot find or open Agent_LinuARM64*.zip, Agent_LinuARM64*.zip.zip or Agent_LinuARM64*.zip.ZIP.

No zipfiles found.

[ERROR] in line 35: exit code 0: while executing command $STD unzip Agent_LinuARM64*.zip`

### Please provide detailed steps to reproduce the issue.

Intall Agent DVR using pimox script

**Comment by asylumexp** [comment]
can you try now?

**Comment by kgsrirama** [comment]
Thanks it is working now :)
